# colors
set-option -sa terminal-overrides ",xterm*:Tc"

# set prefix to Ctrl Space
unbind C-b
# set -g prefix C-Space
# bind C-Space send-prefix
set -g prefix `
bind ` send-prefix

set -g default-command "${SHELL} -l"

# 1 based indexing
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# change status bar position
set-option -g status-position top

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g status-style 'bg=default'

# theme
set -g @plugin 'rose-pine/tmux'
set -g @rose_pine_variant 'moon'
set -g @rose_pine_host 'off'
set -g @rose_pine_date_time ''
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_left_separator ' | '
set -g @rose_pine_right_separator ' '
set -g @rose_pine_field_separator ' '
set -g @rose_pine_window_status_separator ' '
set -g @rose_pine_session_icon '' # Changes the default icon to the left of the session name
set -g @rose_pine_window_status_separator_icon ' ' 
set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_disable_active_window_menu 'on'

set-option -g status-style bg=default

# nerdfront window panes
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @tmux-nerd-font-window-name-show-name true

# set vi-mode
set-window-option -g mode-keys vi
# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# open panes in current directory
bind '"' split-window -v -c '#{pane_current_path}'
bind % split-window -h -c '#{pane_current_path}'

# tmux sessionizer
bind-key -r f run-shell "tmux neww $HOME/.config/tmux/tmux_sessionizer"


# nvim zen mode
set-option -g allow-passthrough on

# initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

# bracket window names (keep at bottom)
set -g window-status-format " #[fg=#c4a7e7,bg=default]#I #[fg=#c4a7e7,bg=default]#W"
set -g window-status-current-format " #[fg=#f6c177,bg=default]#I #[fg=#f6c177,bg=default]#W"
