alias vim='nvim'
alias vi='nvim'
alias tlist='tmux list-sessions'
alias tkill='tmux kill-session -t'
alias tkillser='tmux kill-server'
alias vnv='. venv/bin/activate'
alias cl='clear'
alias syncserv='rsync -av --progress "/mnt/c/Users/catri/Downloads/files_for_server/" "alphacatpotat@192.168.1.107:/media/drive1/Torrents/"'
alias syncpotats='rsync -av --delete --info=progress2 "$HOME/projects/potats-place/astro/dist/" "crowley:/srv/potatsplace/"'
